//! FFI bindings for the PVCAM C SDK.
//!
//! These bindings are generated by `bindgen` during the build process.
//!
//! To use these bindings, the `pvcam-sdk` feature must be enabled, and
//! the `PVCAM_SDK_DIR` environment variable must point to the root
//! directory of your PVCAM SDK installation.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(deref_nullptr)]
#![allow(clippy::all)]

#[cfg(feature = "pvcam-sdk")]
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

#[cfg(feature = "pvcam-sdk")]
pub use bindings::*;

#[cfg(not(feature = "pvcam-sdk"))]
pub mod mock_bindings {
    // ... mock types if needed, or just empty
}

// Manual constant definitions for enums that bindgen didn't export as consts
// Parameter attribute constants (from PL_PARAM_ATTRIBUTES enum)
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_CURRENT: i16 = 0;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_COUNT: i16 = 1;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_TYPE: i16 = 2;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_MIN: i16 = 3;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_MAX: i16 = 4;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_DEFAULT: i16 = 5;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_INCREMENT: i16 = 6;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_ACCESS: i16 = 7;
#[cfg(feature = "pvcam-sdk")]
pub const ATTR_AVAIL: i16 = 8;
#[cfg(feature = "pvcam-sdk")]
pub const TIMED_MODE: i16 = 0;
#[cfg(feature = "pvcam-sdk")]
pub const READOUT_NOT_ACTIVE: i16 = 0;
#[cfg(feature = "pvcam-sdk")]
pub const EXPOSURE_IN_PROGRESS: i16 = 1;
#[cfg(feature = "pvcam-sdk")]
pub const READOUT_IN_PROGRESS: i16 = 2;
#[cfg(feature = "pvcam-sdk")]
pub const READOUT_COMPLETE: i16 = 3;
#[cfg(feature = "pvcam-sdk")]
pub const READOUT_FAILED: i16 = 4;

// Circular buffer modes for pl_exp_setup_cont
//
// IMPORTANT: Prime BSI does NOT support CIRC_OVERWRITE (error 185).
// Use CIRC_NO_OVERWRITE with FIFO draining (pl_exp_get_oldest_frame_ex +
// pl_exp_unlock_oldest_frame) to prevent buffer stalls.
// See: docs/architecture/adr-pvcam-continuous-acquisition.md

/// Circular buffer mode: Overwrite oldest frames when buffer is full.
/// WARNING: NOT supported on Prime BSI cameras (returns error 185).
#[cfg(feature = "pvcam-sdk")]
pub const CIRC_OVERWRITE: i16 = 0;

/// Circular buffer mode: Stop acquisition when buffer is full.
/// Use with FIFO retrieval (`pl_exp_get_oldest_frame_ex` +
/// `pl_exp_unlock_oldest_frame`) to drain buffers safely.
#[cfg(feature = "pvcam-sdk")]
pub const CIRC_NO_OVERWRITE: i16 = 1;

// Exposure modes for sCMOS cameras (bd-3gnv)
// Modern sCMOS cameras require EXT_TRIG_* modes instead of legacy TIMED_MODE.
// These can be ORed with PL_EXPOSE_OUT_MODES values.
#[cfg(feature = "pvcam-sdk")]
pub const EXT_TRIG_INTERNAL: i16 = (7 + 0) << 8; // 1792 - Internal trigger, camera controls timing
#[cfg(feature = "pvcam-sdk")]
pub const EXPOSE_OUT_FIRST_ROW: i16 = 0; // Expose out signal on first row

// Camera Control Subsystem abort modes for pl_exp_stop_cont/pl_exp_abort
#[cfg(feature = "pvcam-sdk")]
pub const CCS_NO_CHANGE: i16 = 0;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_HALT: i16 = 1;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_HALT_CLOSE_SHTR: i16 = 2;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_CLEAR: i16 = 3;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_CLEAR_CLOSE_SHTR: i16 = 4;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_OPEN_SHTR: i16 = 5;
#[cfg(feature = "pvcam-sdk")]
pub const CCS_CLEAR_OPEN_SHTR: i16 = 6;

// Callback event types for pl_cam_register_callback_ex3 (bd-ek9n.2)
#[cfg(feature = "pvcam-sdk")]
pub const PL_CALLBACK_BOF: i32 = 0; // Beginning of frame
#[cfg(feature = "pvcam-sdk")]
pub const PL_CALLBACK_EOF: i32 = 1; // End of frame (frame ready)

// NOTE: FRAME_INFO structure is generated by bindgen from the SDK headers.
// We use the bindgen-generated FRAME_INFO (type alias to _TAG_FRAME_INFO).
// Fields include: FrameInfoGUID, hCam, FrameNr, TimeStamp, ReadoutTime, TimeStampBOF
// FrameNr is the hardware frame number (1-based) used for frame loss detection (bd-ek9n.3).

/// Callback function type for PVCAM EOF callbacks (bd-ek9n.2)
///
/// The callback is invoked by PVCAM on EOF events. Keep work minimal:
/// - Update frame-ready signal
/// - Do NOT block or perform lengthy operations
/// - Frame retrieval happens outside the callback
///
/// Uses `extern "system"` for cross-platform ABI safety:
/// - On Unix: equivalent to `extern "C"` (cdecl)
/// - On Windows: maps to `__stdcall` which PVCAM SDK uses for callbacks
/// - On Windows x64: cdecl and stdcall are unified, so both work
///
/// The callback is cast to `*mut c_void` when registered with PVCAM.
#[cfg(feature = "pvcam-sdk")]
pub type PvcamCallback =
    unsafe extern "system" fn(pFrameInfo: *const FRAME_INFO, pContext: *mut std::ffi::c_void);

// NOTE: pl_cam_register_callback_ex3 and pl_cam_deregister_callback are generated
// by bindgen from the SDK headers. Use the bindgen-generated versions directly.
// Cast PvcamCallback to *mut c_void when calling pl_cam_register_callback_ex3.

#[cfg(not(feature = "pvcam-sdk"))]
/// Placeholder module when the `pvcam-sdk` feature is not enabled.
/// No actual PVCAM functions or types are available in this configuration.
pub mod pvcam_bindings {
    // Define minimal types or functions if needed for API compatibility
    // but for a -sys crate, an empty module is often sufficient.
}
