//! Slint UI module - Generated types and re-exports
//!
//! This module encapsulates the Slint-generated types from the UI definition files.
//! All UI types should be imported from here rather than using slint::include_modules! directly.

mod adapter;

slint::include_modules!();

// Re-export commonly used Slint types for convenience
pub use slint::{ComponentHandle, SharedString, VecModel, Weak};

// Re-export the UiAdapter for clean handler code
pub use adapter::UiAdapter;

// Note: The following types are generated by slint::include_modules!() and 
// available for use: MainWindow, DeviceInfo, SelectedMovable, SelectedReadable,
// SelectedCamera, ScanStatus, ToastMessage, ModuleTypeInfo, ModuleInstance,
// ModuleRole, ModuleParameter, ModuleEvent, ScanConfig, PresetInfo,
// PlanTypeInfo, QueuedPlan, EngineStatusInfo, DocumentInfo (bd-niy4)
