name: 'Setup Rust DAQ Environment'
description: 'Sets up Rust toolchain and system dependencies for rust-daq'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: ''
  rust-toolchain:
    description: 'Rust toolchain to install (stable/nightly/etc)'
    required: false
    default: 'stable'
  components:
    description: 'Rust components to install'
    required: false
    default: ''
  cache-key:
    description: 'Key suffix for rust-cache'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install system dependencies (Linux)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config libhdf5-dev

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-toolchain }}
        components: ${{ inputs.components }}

    - name: Cache cargo
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        shared-key: ${{ inputs.cache-key }}

    - name: Set up Python
      if: inputs.python-version != ''
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
